module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/src'],
  testMatch: ['**/__tests__/**/*.ts', '**/?(*.)+(spec|test).ts'],
  moduleNameMapper: {
    '^@agent/(.*)$': '<rootDir>/src/agent/$1',
    '^@playbooks/(.*)$': '<rootDir>/src/playbooks/$1',
    '^@detectors/(.*)$': '<rootDir>/src/detectors/$1',
    '^@custom-types/(.*)$': '<rootDir>/src/types/$1',
    '^@types/(.*)$': '<rootDir>/src/types/$1',
    '^@utils/(.*)$': '<rootDir>/src/utils/$1',
    '^@config/(.*)$': '<rootDir>/src/config/$1',
    '^@loaders/(.*)$': '<rootDir>/src/loaders/$1',
    '^@data-sources/(.*)$': '<rootDir>/src/data_sources/$1',
    '^@data-providers/(.*)$': '<rootDir>/src/data-providers/$1',
    '^@portfolio/(.*)$': '<rootDir>/src/portfolio/$1',
    '^@sim/(.*)$': '<rootDir>/src/sim/$1',
    '^@runners/(.*)$': '<rootDir>/src/runners/$1',
    '^@signals/(.*)$': '<rootDir>/src/signals/$1',
  },
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/*.d.ts',
    '!src/**/*.test.ts',
  ],
};
