-- ═══════════════════════════════════════════════════════════════
-- Flowrex Trading Journal & Performance Database Schema
-- ═══════════════════════════════════════════════════════════════
-- Database: PostgreSQL 12+
-- Purpose: Store AI signals, trades, tags, and performance metrics
-- ═══════════════════════════════════════════════════════════════

-- signals: Every AI signal generated by Flowrex
CREATE TABLE signals (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  symbol          TEXT NOT NULL,
  instrument      TEXT NOT NULL,
  direction       TEXT NOT NULL,         -- long | short | neutral
  playbook        TEXT NOT NULL,
  primary_playbook TEXT,
  backup_playbook  TEXT,
  confidence      NUMERIC(5,2),
  grade           TEXT,                  -- A | B | C
  reasons         JSONB,                 -- array of strings
  risk_hints      JSONB,                 -- array of strings
  timeframe       TEXT NOT NULL,
  source          TEXT NOT NULL,         -- mt5 | tradingview | live-router | manual
  raw_context     JSONB,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- trades: Journal entries for actual trades
CREATE TABLE trades (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  signal_id       UUID REFERENCES signals(id),
  symbol          TEXT NOT NULL,
  instrument      TEXT NOT NULL,
  direction       TEXT NOT NULL,
  playbook        TEXT NOT NULL,
  entry_time      TIMESTAMPTZ NOT NULL,
  exit_time       TIMESTAMPTZ,
  entry_price     NUMERIC(18,8) NOT NULL,
  exit_price      NUMERIC(18,8),
  size            NUMERIC(18,8) NOT NULL,    -- lot or size
  pnl             NUMERIC(18,8),             -- in account currency
  rr              NUMERIC(10,4),             -- R multiple
  status          TEXT NOT NULL,             -- open | closed | cancelled
  session         TEXT,                      -- Asia | London | NY
  notes           TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- trade_tags: Dictionary of available tags
CREATE TABLE trade_tags (
  id        SERIAL PRIMARY KEY,
  name      TEXT UNIQUE NOT NULL
);

-- trade_tag_links: Many-to-many relationship between trades and tags
CREATE TABLE trade_tag_links (
  trade_id  UUID REFERENCES trades(id) ON DELETE CASCADE,
  tag_id    INT REFERENCES trade_tags(id) ON DELETE CASCADE,
  PRIMARY KEY (trade_id, tag_id)
);

-- Indexes for performance
CREATE INDEX idx_signals_symbol ON signals(symbol);
CREATE INDEX idx_signals_playbook ON signals(playbook);
CREATE INDEX idx_signals_source ON signals(source);
CREATE INDEX idx_signals_created_at ON signals(created_at DESC);

CREATE INDEX idx_trades_symbol ON trades(symbol);
CREATE INDEX idx_trades_playbook ON trades(playbook);
CREATE INDEX idx_trades_status ON trades(status);
CREATE INDEX idx_trades_entry_time ON trades(entry_time DESC);
CREATE INDEX idx_trades_signal_id ON trades(signal_id);

-- Insert some default tags
INSERT INTO trade_tags (name) VALUES
  ('NBB'),
  ('Tori'),
  ('Fabio'),
  ('JadeCap'),
  ('Liquidity Raid'),
  ('Session Open'),
  ('FOMO'),
  ('Revenge Trade'),
  ('Perfect Setup'),
  ('Missed Entry')
ON CONFLICT (name) DO NOTHING;
